import theme from '../../theme/index';
import {StyleSheet, Dimensions, Platform} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';

let headericonOpacity = 0.7;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.color.background,
  },
  Status: {
    backgroundColor: '#fff',
  },
  Header: {
    backgroundColor: '#fff',
    height: 60,
    alignItems: 'center',
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
  },
  header: {
    position: 'absolute',
    top: 13,
    left: 12,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
  },
  CrossButton: {
    height: 30,
    width: 30,
    backgroundColor: '#0E47A1',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  MenuButton: {
    height: 30,
    width: 30,
    marginTop: 15,
    backgroundColor: '#0E47A1',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Body: {
    width: '90%',
    alignSelf: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  markerFixed: {
    left: '50%',
    position: 'absolute',
    top: '50%',
  },

  Input: {
    borderRadius: 20,
    marginTop: 10,
    paddingVertical: 12,
    paddingHorizontal: 10,
    width: '90%',
    alignSelf: 'center',
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Title: {
    fontFamily: 'Inter-Bold',
    fontSize: 22,
    color: '#000',
  },
  Dot: {
    height: 10,
    width: 10,
    borderRadius: 10,
    backgroundColor: '#0E47A1',
  },
  Button: {
    height: 48,
    borderRadius: 48,
    marginTop: 10,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#0E47A1',
    justifyContent: 'center',
  },
  ButtonText: {
    alignSelf: 'center',
    color: '#fff',
    fontFamily: 'Inter-Bold',
    fontSize: 16,
  },

  dropOff: {
    marginTop: 10,
    padding: 10,
    width: '100%',
    alignSelf: 'center',
  },
  catImg: {width: 45, height: 45},
  headerPosition: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: theme.color.background,
    position: 'absolute',
    elevation: 10,
    width: '100%',
    top: Platform.OS == 'ios' ? theme.window.APPBAR_HEIGHT : 0,
  },
  crossButton: {
    width: 30,
    opacity: headericonOpacity,
    backgroundColor: 'white',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    height: 30,
    // elevation: 7,
    marginTop: 5,
  },
  googleSearchBar: {
    width: 200,
    height: 40,
    backgroundColor: 'white',
    borderRadius: 12,
    opacity: headericonOpacity,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    elevation: 7,
  },
  googleSearchBarText: {
    fontSize: 13,
    color: 'black',
    marginLeft: 10,
    fontFamily: theme.fonts.fontMedium,
  },
  currentLocationButton: {
    width: 40,
    backgroundColor: 'white',
    opacity: headericonOpacity,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    height: 40,
    elevation: 7,
    position: 'absolute',
    bottom: responsiveHeight(Platform.OS == 'android' ? 10 : 12),
    right: 10,
  },
  BottomView: {
    width: '100%',
    backgroundColor: theme.color.button1,
    height: responsiveHeight(8),
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    position: 'absolute',
    bottom: Platform.OS == 'android' ? 0 : theme.window.STATUSBAR_HEIGHT + 20,
  },
  section1Container: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',

    width: '100%',
    height: responsiveHeight(8),
  },
  section11: {
    width: '10%',
  },
  section12: {
    width: '87%',
  },
  section12TextTitle: {
    color: theme.color.title,
    fontSize: 17,
    fontFamily: theme.fonts.fontMedium,
    lineHeight: 20,
  },
  section12TextSubTitle: {
    color: theme.color.subTitle,
    fontSize: 14,
    fontFamily: theme.fonts.fontNormal,
  },
  section2: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    backgroundColor: theme.color.background,
    borderRadius: 7,
    alignSelf: 'center',
    marginTop: 10,
    elevation: 4,
  },
  LinearGradient: {
    height: '100%',
    width: '100%',
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  section2Text: {
    color: theme.color.buttonText,
    fontSize: 16,
    fontFamily: theme.fonts.fontBold,
  },
  section2DisbaleText: {
    color: theme.color.buttonText,
    fontSize: 13,
    fontFamily: theme.fonts.fontBold,
    lineHeight: 20,
  },
  dotPosition: {
    left: '50%',
    position: 'absolute',
    top: '50%',
  },
  dot: {
    width: 30,
    height: 30,
    borderRadius: 6,
    backgroundColor: 'black',
  },
  dotWarningMessage: {
    backgroundColor: 'white',
    opacity: 0.8,
    bottom: 20,
    alignSelf: 'center',
    position: 'absolute',
    width: responsiveWidth(47),
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    borderRadius: 10,
  },
  dotWarningMessageText: {
    fontSize: 12,
    color: theme.color.title,
    fontFamily: theme.fonts.fontMedium,
  },
});

export default styles;
