import theme from '../../theme/index';
import {StyleSheet, Dimensions, Platform} from 'react-native';
import {
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';

let headericonOpacity = 0.7;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.color.background,
  },
  Status: {
    backgroundColor: '#fff',
  },
  Header: {
    backgroundColor: '#fff',
    height: 60,
    alignItems: 'center',
    flexDirection: 'row',
    width: '90%',
    alignSelf: 'center',
  },
  header: {
    position: 'absolute',
    top: 13,
    left: 12,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
  },
  CrossButton: {
    height: 30,
    width: 30,
    backgroundColor: '#0E47A1',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  MenuButton: {
    height: 30,
    width: 30,
    marginTop: 15,
    backgroundColor: '#0E47A1',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  Body: {
    width: '90%',
    alignSelf: 'center',
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  markerFixed: {
    left: '50%',
    position: 'absolute',
    top: '50%',
  },

  Input: {
    borderRadius: 20,
    marginTop: 10,
    paddingVertical: 12,
    paddingHorizontal: 10,
    width: '90%',
    alignSelf: 'center',
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  Title: {
    fontFamily: 'Inter-Bold',
    fontSize: 22,
    color: '#000',
  },
  Dot: {
    height: 10,
    width: 10,
    borderRadius: 10,
    backgroundColor: '#0E47A1',
  },
  Button: {
    height: 48,
    borderRadius: 48,
    marginTop: 10,
    width: '100%',
    alignSelf: 'center',
    backgroundColor: '#0E47A1',
    justifyContent: 'center',
  },
  ButtonText: {
    alignSelf: 'center',
    color: '#fff',
    fontFamily: 'Inter-Bold',
    fontSize: 16,
  },

  dropOff: {
    marginTop: 10,
    padding: 10,
    width: '100%',
    alignSelf: 'center',
  },
  catImg: {width: 45, height: 45},
  headerPosition: {
    flexDirection: 'row',
    // alignItems: 'center',
    paddingHorizontal: 15,
    justifyContent: 'space-between',
    position: 'absolute',
    top: 0,
    width: '100%',
    backgroundColor: theme.color.background,
    paddingVertical: Platform.OS == 'ios' ? theme.window.APPBAR_HEIGHT : 15,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    elevation: 5,
  },
  crossButton: {
    width: 40,
    opacity: headericonOpacity,
    backgroundColor: theme.color.background,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    height: 37,
  },
  googleSearchBar: {
    width: '100%',
    height: '100%',
    paddingHorizontal: 15,
    justifyContent: 'center',
  },
  googleSearchBarText: {
    fontSize: 13,
    color: theme.color.subTitleLight,

    fontFamily: theme.fonts.fontNormal,
  },
  currentLocationButton: {
    width: 37,
    alignItems: 'center',
    justifyContent: 'center',
    height: 37,

    position: 'absolute',
    right: 0,
  },
  clearButton: {
    width: 37,
    alignItems: 'center',
    justifyContent: 'center',
    height: 37,

    position: 'absolute',
    right: 30,
  },
  clearButton2: {
    width: 17,
    alignItems: 'center',
    justifyContent: 'center',
    height: 17,
    backgroundColor: '#E8E8E899',

    borderColor: theme.color.subTitleLight,
    borderWidth: 1,
    borderRadius: 17 / 2,
  },
  BottomView: {
    width: '100%',
    backgroundColor: 'white',
    paddingHorizontal: 15,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
    position: 'absolute',
    zIndex: 3,
    bottom: 0,
  },
  section1Container: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    height: responsiveHeight(8),
    marginBottom: Platform.OS == 'ios' ? 10 : 0,
  },
  section11: {
    width: '10%',
  },
  section12: {
    width: '87%',
  },
  section12TextTitle: {
    color: theme.color.title,
    fontSize: 17,
    fontFamily: theme.fonts.fontMedium,
    lineHeight: 20,
  },
  section12TextSubTitle: {
    color: theme.color.subTitle,
    fontSize: 14,
    fontFamily: theme.fonts.fontNormal,
  },
  section2: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    height: responsiveHeight(5.5),
    backgroundColor: theme.color.button1,
    borderRadius: 7,
    alignSelf: 'center',
    marginTop: 10,
    elevation: 4,
    marginBottom: Platform.OS == 'ios' ? theme.window.APPBAR_HEIGHT : 0,
  },
  LinearGradient: {
    height: '100%',
    width: '100%',
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  section2Text: {
    color: theme.color.buttonText,
    fontSize: 16,
    fontFamily: theme.fonts.fontBold,
    textTransform: 'capitalize',
  },

  dotPosition: {
    left: '50%',
    position: 'absolute',
    top: '50%',
  },
  dot: {
    width: 30,
    height: 30,
    borderRadius: 6,
    backgroundColor: 'black',
  },
  dotWarningMessage: {
    backgroundColor: 'white',
    opacity: 0.8,
    bottom: 12,
    alignSelf: 'center',
    position: 'absolute',
    width: responsiveWidth(47),
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
    borderRadius: 10,
  },
  dotWarningMessageText: {
    fontSize: 12,
    color: theme.color.title,
    fontFamily: theme.fonts.fontMedium,
  },

  BottomButton: {
    width: '85%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.color.button1,
    height: 47,
    borderRadius: 10,
    alignSelf: 'center',
    elevation: 1.5,
    position: 'absolute',
    zIndex: 3,
    bottom: Platform.OS == 'android' ? 30 : theme.window.APPBAR_HEIGHT + 15,
  },
  buttonTextBottom: {
    color: theme.color.buttonText,
    fontSize: 15,
    fontFamily: theme.fonts.fontMedium,
    textTransform: 'capitalize',
  },
});

export default styles;
